services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
    command: >
      uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expo-frontend
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend
